### ISSUE TITLE
Provide default configs from CT release

### ISSUE THREAD

**Issue by lafriks** [ventx/helm3-ci#16]
Currently from release archive only ct binary is extracted but not contents of `/etc/ct` folder thus breaking upgrades from 1.0.1 and forcing to needlessly add CT lint configuration to every repository. As per docs CT will look for these files in `/etc/ct` if not specified in command line but currently if not specified it fails with error that files can not be found.

Related to #1

**Comment by hajowieland** [comment]
I just a released version `2.4.0` which includes the default chart-testing configuration files located at /etc/ct.

Would you mind testing it if it now works as expected?

**Comment by lafriks** [comment]
Tested with 2.5.0 and it works great, thanks
